### ISSUE TITLE
TiKV compatibility tracking issue

### ISSUE THREAD

**Issue by iosmanthus** [tikv/client-java#464]
## Feature Request

Currently, client-java's features are always catching to the latest version of TiKV, it is hard to select the version of TiKV with a specific version of client-java. We are only tracking the compatibility of **master** and **release-3.1's** integration tests without each specific API.

Release-3.1 is fully compatible with TiKV (5.0.x - 5.3.x).
The master branch has been discovered the issue: https://github.com/tikv/client-java/issues/462.

**Describe the feature you'd like:**
To draw the full compatibility matrix, we need:
- [x] introducing version constraint on some tests, fix #462 by https://github.com/tikv/client-java/pull/463.
- [ ] **use integration tests to cover every exported API, e.g. `RawKVClient`, `PDClient`**
- [ ] create another autotest in Jenkins and run integration tests on different branches of TiKV.
- [ ] run regression tests on every new minor/major version of TiKV.
