### ISSUE TITLE
TiKV API V2 Testing Tracking issue

### ISSUE THREAD

**Issue by iosmanthus** [tikv/client-java#582]
This issue is a tracking issue of the TiKV API V2 feature of `client-java`.

For now, the API version is attached to request contexts and the key prefix is also prepended according to the API version: https://github.com/tikv/client-java/pull/575. The rest of the work is working on the test for the feature:

- [ ] A CI matrix with dimensions of API version and TTL mode.
- [ ] Test framework of checking the API/TTL config of a TiKV cluster.
- [ ] Test that runs only with a specific API/TTL config. (using the `Assume` guard, e.g. `Assume.assumeTrue(getServerApiVersion().isV1() && getServerTTLEnabled())`)
- [ ] Tests cover the API compatible matrix: https://github.com/pingyu/tikv-rfcs/blob/rfc_api_v2_pd/text/0069-api-v2.md#tikv-client

**Comment by GOODBOY008** [comment]
@iosmanthus When use this client to get table(partion table) data,client return nothing with set tableId.But with partion id,worked normally.

**Comment by iosmanthus** [comment]
If you are using client-java to read TiDB table, please use V1 instead.

**Comment by GOODBOY008** [comment]
> If you are using client-java to read TiDB table, please use V1 instead.

I also want to capture real-time data changes of table in project flink-cdc-connectors.
